# Generated by Django 4.0 on 2021-12-23 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapi', '0002_alter_rental_customer_delete_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='poster',
        ),
    ]
