# Generated by Django 4.0 on 2021-12-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapi', '0003_remove_movie_poster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='customer',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='returned_at',
        ),
        migrations.AddField(
            model_name='rental',
            name='activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rental',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
        ),
        migrations.AddField(
            model_name='rental',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='category',
        ),
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.ManyToManyField(related_name='movies', to='storeapi.Category'),
        ),
    ]
