# Generated by Django 4.0 on 2021-12-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapi', '0004_rename_customer_rental_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='price',
            field=models.FloatField(default=1.0),
        ),
    ]
