# Generated by Django 4.0 on 2021-12-26 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapi', '0005_alter_rental_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='rented_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 26, 13, 32, 14, 51710)),
        ),
    ]
