# Generated by Django 4.0 on 2021-12-26 13:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('storeapi', '0007_alter_rental_rented_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='rented_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
