version: '3.3'

services:
  app:
    build:
      context: .
    command: >
      sh -c "python manage.py wait_for_db && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ./moviestore:/moviestore
    environment:
      - DJANGO_SECRET_KEY=devsecretkey
      - DJANGO_DEBUG=1
      - DB_HOST=db
      - DB_NAME=moviestoredb
      - DB_USER=moviestoreuser
      - DB_PASSWORD=moviestorepassword
    depends_on:
      - db
      
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=moviestoredb
      - POSTGRES_USER=moviestoreuser
      - POSTGRES_PASSWORD=moviestorepassword